### ISSUE TITLE
Create percentage transfer rule

### ISSUE THREAD

**Issue by dat2** [dat2/financial-planner-cli#12]
A possible input format:

```yaml
accounts:
  assets:
    stocks:
      amount: 1000
rules:
  'Reinvest Dividends':
    from: 'assets:stocks'
    to: 'assets:stocks'
    percentage: 3%
    frequency: Quarterly
    start_date: '2017-01-01'
```
