### ISSUE TITLE
Add Calculated Accounts (eg. Profit)

### ISSUE THREAD

**Issue by dat2** [dat2/financial-planner-cli#6]
A possible input format could look like this:

```yaml
accounts:
  net:
    expression: 'assets - liabilities'
```
