### ISSUE TITLE
Create a rule representing asset return values.

### ISSUE THREAD

**Issue by dat2** [dat2/financial-planner-cli#9]
A possible format:

```yaml
accounts:
  assets:
    stocks:
      amount: 1000
rules:
  'Return on Stocks':
    roi: 5%
    account: 'assets:stocks'
    frequency: Yearly
```
